# variables + numbers

x = 10
y = 5

print(x + y)
print(x - y)
print(x * y)
print(x / y)

# strings

msg = "hello tk"
print(msg)

# comparison + if

if (x > y) {
    print("x greater")
}

# while loop

i = 0

while (i < 3) {
    print(i)
    i = i + 1
}

# lists

nums = [1,2,3]

print(len(nums))

# for loop

for n in nums {
    print(n)
}

# function with parameters

function add(a,b) {
    print(a + b)
}

add(7,8)

# file loading

data = load("tests/sample.csv")

print(len(data))